const songs=[
{id:1,title:"Uske Naam",artist:"Prasenjit Creations",album:"MELORA EP-5",emoji:"✦",duration:"3:42",lyrics:"Raat ke khamosh lamhon mein\\nTera naam sa sunai de...\\nJo tha mera, woh khwab tha\\nPhir bhi dil tujhe bulaye re..."},
{id:2,title:"O Mere Khuda",artist:"Prasenjit Das",album:"MELORA Rain Sessions",emoji:"☂",duration:"4:08",lyrics:"Bheegi si raat, bheegi si yaadein\\nTere bina sab adhoora...\\nO mere khuda, itna bata\\nKyun dil hai ab bhi tera..."},
{id:3,title:"Tu Rahe Ya Na Rahe",artist:"MELORA Originals",album:"EP-4",emoji:"♡",duration:"3:56",lyrics:"Tu rahe ya na rahe\\nTeri khushboo rahegi...\\nMeri har ek dua mein\\nTeri duniya rahegi..."},
{id:4,title:"Itni Door",artist:"Prasenjit Creations",album:"EP-3",emoji:"◌",duration:"3:31",lyrics:"Itni door kyun ho tum\\nPhir bhi dil ke paas...\\nKhamoshi ke sheher mein\\nTeri hi hai awaaz..."},
{id:5,title:"Jane De Mujhe",artist:"MELORA",album:"Sad Rock EP-2",emoji:"⚡",duration:"4:12",lyrics:"Jane de mujhe, jaane de\\nAb na rok mujhe...\\nToote hue raaston pe\\nKhud ko dhoondne de..."},
{id:6,title:"Aankhon Se Chhu Liya",artist:"MELORA Originals",album:"Romance",emoji:"☾",duration:"3:38",lyrics:"Aankhon se chhu liya\\nDil ne tujhe keh diya...\\nBina kahe jo kehna tha\\nWoh ishq ban gaya..."}
];
let liked=JSON.parse(localStorage.getItem("melora-liked")||"[]");
let current=null,playing=false;
const content=document.getElementById("content");
const toastEl=document.getElementById("toast");
function toast(t){toastEl.textContent=t;toastEl.classList.add("show");setTimeout(()=>toastEl.classList.remove("show"),1800)}
function art(s){return `<div class="art">${s.emoji}<span>${s.album}</span><button class="play-float" onclick="event.stopPropagation();playSong(${s.id})">▶</button></div>`}
function cards(list){return `<div class="cards">${list.map(s=>`<div class="card" onclick="playSong(${s.id})">${art(s)}<h3>${s.title}</h3><p>${s.artist}</p></div>`).join("")}</div>`}
function tracks(list){return `<div class="tracks">${list.map(s=>`<div class="track"><div class="track-art">${s.emoji}</div><div><strong>${s.title}</strong><small>${s.artist} · ${s.album}</small></div><time>${s.duration}</time><button class="heart ${liked.includes(s.id)?"liked":""}" onclick="toggleLike(event,${s.id})">${liked.includes(s.id)?"♥":"♡"}</button></div>`).join("")}</div>`}
function home(){content.innerHTML=`<div class="page"><div class="hero"><div><div class="eyebrow">WELCOME TO MELORA</div><h1>Music that understands your mood.</h1><p>Discover original sounds, cinematic melodies and songs made for every version of you.</p><button class="primary" onclick="playSong(1)">▶ Start listening</button><button class="ghost" onclick="go('discover')">Explore</button></div></div><div class="section-head"><h2>Made for you</h2><button onclick="go('discover')">See all</button></div>${cards(songs.slice(0,5))}<div class="section-head"><h2>Quick moods</h2></div><div class="moods">${["Chill","Romantic","Sad","Night Drive","Focus","Horror","Rainy Night"].map(x=>`<button class="mood" onclick="mood('${x}')">${x}</button>`).join("")}</div><div class="section-head"><h2>Recently added</h2></div>${tracks(songs.slice(0,4))}</div>`}
function discover(){content.innerHTML=`<div class="page"><div class="section-head"><h2>Discover</h2></div><div class="ai-box"><div class="eyebrow">MELORA AI</div><h2>Create a playlist from a feeling.</h2><p style="color:#85858e">Tell MELORA what you want to hear.</p><input id="aiPrompt" placeholder="e.g. rainy night, alone, cinematic"><button class="primary" style="margin-left:8px" onclick="generateAI()">Generate</button><div class="results" id="aiResults"></div></div><div class="section-head"><h2>Trending on MELORA</h2></div>${cards(songs)}<div class="section-head"><h2>Browse by mood</h2></div><div class="moods">${["Chill","Romantic","Sad","Night Drive","Focus","Horror","Rainy Night"].map(x=>`<button class="mood" onclick="mood('${x}')">${x}</button>`).join("")}</div></div>`}
function library(){content.innerHTML=`<div class="page"><div class="section-head"><h2>Your Library</h2></div>${tracks(songs)}<div class="section-head"><h2>Albums</h2></div>${cards(songs.slice(0,4))}</div>`}
function playlists(){content.innerHTML=`<div class="page"><div class="section-head"><h2>Your Playlists</h2><button onclick="toast('New playlist created')">＋ New playlist</button></div><div class="cards">${["Midnight Melodies","Broken Hearts","Rain & Memories","Japanese Night","Horror Vibes"].map((x,i)=>`<div class="card" onclick="toast('${x} opened')"><div class="art">${["☾","♡","☂","夜","☠"][i]}</div><h3>${x}</h3><p>${6+i*3} songs</p></div>`).join("")}</div></div>`}
function likedPage(){const ls=songs.filter(s=>liked.includes(s.id));content.innerHTML=`<div class="page"><div class="section-head"><h2>Liked Songs</h2></div>${ls.length?tracks(ls):`<div class="empty">You haven't liked any songs yet.<br>Tap ♡ beside a song to save it here.</div>`}</div>`}
function downloads(){content.innerHTML=`<div class="page"><div class="section-head"><h2>Downloads</h2></div><div class="empty">Offline downloads are ready for the full MELORA app.<br><br><button class="primary" onclick="toast('Download feature demo')">Try demo</button></div></div>`}
function mood(m){const map={Sad:[1,5,3],Romantic:[1,3,6],Chill:[2,4,6],"Night Drive":[5,4,2],Focus:[4,6,2],Horror:[5,2,4],"Rainy Night":[2,1,3]};const list=(map[m]||[1,2,3]).map(id=>songs.find(s=>s.id===id));content.innerHTML=`<div class="page"><div class="section-head"><h2>${m} mood</h2></div><p style="color:#777">A MELORA mix for your ${m.toLowerCase()} moment.</p>${tracks(list)}</div>`}
function generateAI(){const p=(document.getElementById("aiPrompt").value||"your mood").toLowerCase();const pick=p.includes("sad")||p.includes("alone")?[5,1,3]:p.includes("rain")?[2,1,4]:p.includes("rom")?[3,6,1]:[1,2,5];const list=pick.map(id=>songs.find(s=>s.id===id));document.getElementById("aiResults").innerHTML=`<h3>✨ MELORA Mix: ${p}</h3>${tracks(list)}`;toast("AI playlist generated")}
function toggleLike(e,id){e.stopPropagation();liked=liked.includes(id)?liked.filter(x=>x!==id):[...liked,id];localStorage.setItem("melora-liked",JSON.stringify(liked));document.getElementById("likeCount").textContent=liked.length;toast(liked.includes(id)?"Added to Liked Songs":"Removed from Liked Songs");if(document.querySelector(".nav.active")?.dataset.page==="liked")likedPage()}
function playSong(id){current=songs.find(s=>s.id===id);playing=true;document.getElementById("playerTitle").textContent=current.title;document.getElementById("playerArtist").textContent=current.artist;document.getElementById("playerCover").textContent=current.emoji;document.getElementById("play").textContent="Ⅱ";toast("Playing "+current.title)}
function go(page){document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===page));({home,discover,library,playlists,liked:likedPage,downloads}[page]||home)()}
document.querySelectorAll(".nav").forEach(n=>n.addEventListener("click",()=>go(n.dataset.page)));
document.getElementById("play").onclick=()=>{if(!current){playSong(1);return}playing=!playing;document.getElementById("play").textContent=playing?"Ⅱ":"▶";toast(playing?"Playing":"Paused")};
document.getElementById("next").onclick=()=>playSong(songs[(songs.findIndex(x=>x.id===current?.id)+1)%songs.length].id);
document.getElementById("prev").onclick=()=>playSong(songs[(songs.findIndex(x=>x.id===current?.id)-1+songs.length)%songs.length].id);
document.getElementById("lyricsBtn").onclick=()=>{if(!current){toast("Choose a song first");return}document.getElementById("lyricsTitle").textContent=current.title;document.getElementById("lyricsText").textContent=current.lyrics;document.getElementById("lyricsModal").classList.add("show")};
document.getElementById("closeLyrics").onclick=()=>document.getElementById("lyricsModal").classList.remove("show");
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("ambient");toast("Ambient mode toggled")};
document.getElementById("mobileMenu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
document.getElementById("search").addEventListener("input",e=>{const q=e.target.value.toLowerCase().trim();if(!q){home();return}const r=songs.filter(s=>(s.title+s.artist+s.album).toLowerCase().includes(q));content.innerHTML=`<div class="page"><div class="section-head"><h2>Search results</h2></div>${r.length?tracks(r):`<div class="empty">No MELORA results for “${q}”.</div>`}</div>`});
document.getElementById("likeCount").textContent=liked.length;
home();
